### ISSUE TITLE
Crash calling initLoader

### ISSUE THREAD

**Issue by Wavesonics** [kmdupr33/RxLoader#10]
```
IllegalStateException: Called while creating a loader
at android.support.v4.app.LoaderManagerImpl.initLoader(LoaderManager.java:594)
at com.philosophicalhacker.lib.RxLoader$LoaderCallbackAsyncEmitter.call(RxLoader.java:101)
```

It looks like a race condition inside:
`LoaderCallbackAsyncEmitter`

LoaderManager's initLoader has a guard around some code while it's installing a loader, and if you call any of the methods that install another loader, it throws:
```
    public <D> Loader<D> initLoader(int id, Bundle args, LoaderManager.LoaderCallbacks<D> callback) {
        if (mCreatingLoader) {
            throw new IllegalStateException("Called while creating a loader");
        }
```

It looks to me like we have to protect against that, possibly by throwing a `synchronized` around the contents of `LoaderCallbackAsyncEmitter`'s call method:
```
@Override
public void call(final Emitter<T> emitter) {
    synchronized( mLoaderManager )
    {
        final Loader<T> tLoader
		        = mLoaderManager.initLoader( mId, null,
		                                     new LoaderManager.LoaderCallbacks<T>()
		                                     {
			                                     ...
		                                     } );
        if (mForceReload) {
	        tLoader.forceLoad();
        }
    }
}
```

I've tested this and it seems to work.

**Comment by kmdupr33** [comment]
Can you post the code that caused this? I'm guessing this is happening when creating multiple RxLoader `Observables` because the `Observable` creation (and thus `LoaderManager.init` call) happens off the main thread.

**Comment by kmdupr33** [comment]
This could actually be solved as long as users don't use `subscribeOn` on the transformed `Observable`. Technically, this is unneeded because `subscribeOn` has to be called on the upstream `Observable` that's passed into the transformer.
